on:
  pull_request:
    branches: [ master ]

jobs:
  go-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: awk '$1=="go"{print $2}' go.mod | xargs -I {} echo "::set-output name=version::{}"
        id: go_mod

      - uses: actions/setup-go@v1
        with:
          go-version: ${{ steps.go_mod.outputs.version }}

      - run: go test ./...